import { StyleSheet } from 'react-native';
import { THEME } from '../constants/theme';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: THEME.backgroundDark,
  },
  chrome: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.4,
  },
  gridLine: {
    position: 'absolute',
    top: '18%',
    left: '-25%',
    width: '150%',
    height: 1,
    backgroundColor: 'rgba(245, 4, 4, 0.22)',
    transform: [{ rotate: '-14deg' }],
  },
  gridLineOffset: {
    top: '62%',
    left: '-10%',
  },
  backGlow: {
    position: 'absolute',
    borderRadius: 999,
  },
  replayButton: {
    position: 'absolute',
    top: 58,
    left: 20,
    zIndex: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: THEME.backgroundDark,
    borderWidth: 1,
    borderColor: THEME.primaryGreen,
  },
  replayButtonText: {
    color: THEME.textGray2,
    fontSize: 14,
    fontFamily: THEME.fontMontserrat,
    letterSpacing: 0.3,
  },
  shell: {
    width: '100%',
    maxWidth: 420,
    paddingHorizontal: 24,
    alignItems: 'center',
  },
  headerBlock: {
    gap: 10,
    alignItems: 'center',
    marginBottom: 28,
  },
  kicker: {
    color: THEME.textGray,
    fontSize: 12,
    fontFamily: THEME.fontMontserrat,
    letterSpacing: 2.4,
  },
  title: {
    color: THEME.textLight,
    fontSize: 38,
    fontFamily: THEME.fontMontserrat,
    textAlign: 'center',
    letterSpacing: -1.2,
  },
  titleCompact: {
    fontSize: 34,
  },
  subtitle: {
    color: THEME.textGray,
    fontSize: 16,
    lineHeight: 24,
    fontFamily: THEME.fontNunito,
    textAlign: 'center',
    maxWidth: 320,
  },
  subtitleCompact: {
    fontSize: 15,
    lineHeight: 22,
  },
  scoreCard: {
    width: '100%',
    borderRadius: 30,
    overflow: 'hidden',
    shadowColor: THEME.primaryGreen,
    shadowOpacity: 0.24,
    shadowRadius: 28,
    shadowOffset: {
      width: 0,
      height: 20,
    },
    elevation: 14,
    backgroundColor: THEME.backgroundDark,
  },
  scoreCardGradient: {
    borderRadius: 30,
    paddingVertical: 30,
    paddingHorizontal: 24,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: THEME.backgroundLight,
    backgroundColor: 'rgba(169, 249, 158, 0.16)',
  },
  scoreLabel: {
    color: THEME.textGray,
    fontSize: 13,
    fontFamily: THEME.fontMontserrat,
    letterSpacing: 1.8,
    textTransform: 'uppercase',
  },
  scoreValue: {
    marginTop: 10,
    color: THEME.textLight,
    fontSize: 64,
    fontFamily: THEME.fontMontserrat,
    letterSpacing: -2.6,
    textAlign: 'center',
    minWidth: '100%',
  },
  scoreValueCompact: {
    fontSize: 56,
  },
  scoreHint: {
    marginTop: 8,
    color: THEME.textLight,
    fontSize: 14,
    fontFamily: THEME.fontNunito,
  },
  comboBadge: {
    marginTop: 22,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 999,
    backgroundColor: THEME.primaryGreen3,
    borderWidth: 1,
    borderColor: THEME.backgroundLight,
  },
  comboFlame: {
    fontSize: 20,
  },
  comboText: {
    color: THEME.textLight,
    fontSize: 18,
    fontFamily: THEME.fontNunito,
    letterSpacing: 0.2,
  },
  rankCard: {
    width: '100%',
    marginTop: 20,
    paddingHorizontal: 22,
    paddingVertical: 18,
    borderRadius: 22,
    backgroundColor: THEME.backgroundDark,
    borderWidth: 1,
    borderColor: 'rgba(169, 249, 158, 0.72)',
  },
  rankLabel: {
    color: THEME.textGray,
    fontSize: 13,
    fontFamily: THEME.fontMontserrat,
    letterSpacing: 1.6,
    textTransform: 'uppercase',
  },
  rankValue: {
    marginTop: 8,
    color: THEME.textGray2,
    fontSize: 32,
    fontFamily: THEME.fontMontserrat,
    letterSpacing: -0.8,
  },
  rankMeta: {
    color: THEME.textGray,
    fontSize: 24,
    fontFamily: THEME.fontNunito,
  },
  shareWrap: {
    width: '100%',
    marginTop: 22,
  },
  shareHitbox: {
    borderRadius: 22,
    overflow: 'hidden',
  },
  shareButton: {
    paddingVertical: 18,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  shimmer: {
    position: 'absolute',
    top: -20,
    bottom: -20,
    width: 66,
  },
  shareText: {
    color: THEME.textDark,
    fontSize: 18,
    fontFamily: THEME.fontMontserrat,
    letterSpacing: 0.2,
  },
});
